#!/usr/bin/with-contenv bash
# shellcheck shell=bash

setcap 'cap_net_bind_service=+ep' /usr/bin/python3.10

exec \
    s6-notifyoncheck -d -n 60 -w 5000 -c "nc -z localhost 8123" \
    s6-setuidgid abc /usr/bin/hass -c /config
