#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# set permissions
lsiown -R abc:abc \
    /config
find /lsiopy -path /lsiopy/lib/python3.11/site-packages -prune -o -exec chown abc:abc {} +
lsiown abc:abc /lsiopy/lib/python3.11/site-packages
